-- Initial schema for a fresh Ombrelune database.

-- Apply this migration once, then load supabase/seed.sql if sample data is required.

create extension if not exists pgcrypto with schema extensions;

-- Tables

create table public.employes (
  id bigint generated by default as identity primary key,
  nom_prenom text not null,
  grade text not null default 'Étudiant'
    check (grade in ('Patron', 'Co-Patron', 'Adulte', 'Étudiant')),
  prime_actuelle numeric(14, 2) not null default 0,
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.catalogue (
  id bigint generated by default as identity primary key,
  article text not null,
  categorie text not null default 'Objet'
    check (categorie in ('Objet', 'Ingrédient', 'Permis')),
  prix_achat numeric(14, 2) not null default 0 check (prix_achat >= 0),
  prix_vente numeric(14, 2) not null default 0 check (prix_vente >= 0),
  cout_craft_po numeric(14, 2) not null default 0 check (cout_craft_po >= 0),
  type_article text not null default 'objet'
    check (type_article in ('objet', 'ingredient', 'ticket', 'document_permis')),
  type_permis text check (type_permis in ('Balais', 'Voiture', 'Moto')),
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.clients (
  id bigint generated by default as identity primary key,
  nom_prenom text not null,
  hibou text,
  created_by bigint references public.employes(id) on delete set null,
  updated_by bigint references public.employes(id) on delete set null,
  tickets_retires smallint not null default 0 check (tickets_retires between 0 and 2),
  ticket_session date,
  archived_by bigint references public.employes(id) on delete set null,
  archived_at timestamptz,
  archive_reason text check (archive_reason is null or archive_reason in ('departure', 'death', 'other')),
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.stocks (
  id bigint generated by default as identity primary key,
  article_id bigint not null unique references public.catalogue(id) on delete cascade,
  quantite integer not null default 0 check (quantite >= 0),
  stock_max integer check (stock_max is null or stock_max >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.recettes_craft (
  id bigint generated by default as identity primary key,
  produit_id bigint not null references public.catalogue(id) on delete cascade,
  ingredient_id bigint not null references public.catalogue(id) on delete cascade,
  quantite_requise integer not null default 1 check (quantite_requise > 0),
  quantite_produite integer not null default 1 check (quantite_produite > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (produit_id, ingredient_id),
  check (produit_id <> ingredient_id)
);

create table public.periodes_comptables (
  id bigint generated by default as identity primary key,
  date_debut date not null,
  date_fin date,
  statut text not null default 'ouverte' check (statut in ('ouverte', 'clôturée')),
  ca_total numeric(14, 2) not null default 0,
  depenses numeric(14, 2) not null default 0,
  benefice_brut numeric(14, 2) not null default 0,
  taxes numeric(14, 2) not null default 0,
  salaires_primes numeric(14, 2) not null default 0,
  benefice_net numeric(14, 2) not null default 0,
  nombre_ventes integer not null default 0 check (nombre_ventes >= 0),
  nombre_achats integer not null default 0 check (nombre_achats >= 0),
  nombre_crafts integer not null default 0 check (nombre_crafts >= 0),
  cloturee_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint periodes_comptables_sans_chevauchement
    exclude using gist (daterange(date_debut, coalesce(date_fin, 'infinity'::date), '[]') with &&),
  check (date_fin is null or date_fin >= date_debut),
  check (
    (statut = 'ouverte' and date_fin is null and cloturee_at is null)
    or (statut = 'clôturée' and date_fin is not null and cloturee_at is not null)
  )
);

create table public.transactions (
  id bigint generated by default as identity primary key,
  periode_id bigint not null references public.periodes_comptables(id) on delete restrict,
  date_transaction date not null default current_date,
  vendeur_id bigint references public.employes(id) on delete set null,
  vendeur_nom text,
  article_id bigint references public.catalogue(id) on delete set null,
  article_nom text,
  quantite integer not null default 1 check (quantite > 0),
  prix_unitaire numeric(14, 2),
  prix_total numeric(14, 2) not null default 0,
  benefice_total numeric(14, 2),
  type_transaction text not null,
  created_at timestamptz not null default now()
);

create table public.commandes (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  client_nom text,
  employe_id bigint references public.employes(id) on delete set null,
  employe_nom text,
  date_commande date not null default current_date,
  date_livraison date not null,
  date_pret date,
  contenu text,
  prix_total numeric(14, 2) not null default 0,
  statut_paiement text not null default 'En attente'
    check (statut_paiement in ('En attente', 'Payé')),
  statut_livraison text not null default 'En préparation'
    check (statut_livraison in ('En préparation', 'Prêt', 'Livré', 'Annulée')),
  statut_avant_annulation text
    check (statut_avant_annulation in ('En préparation', 'Prêt')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.lignes_commandes (
  id bigint generated by default as identity primary key,
  commande_id bigint not null references public.commandes(id) on delete cascade,
  article_id bigint not null references public.catalogue(id) on delete restrict,
  article_nom text not null,
  quantite integer not null check (quantite > 0),
  prix_unitaire numeric(14, 2) not null check (prix_unitaire >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (commande_id, article_id)
);

create table public.registre_tickets (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  quantite integer not null default 1 check (quantite > 0),
  date_session date not null,
  transaction_id bigint references public.transactions(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.registre_tresorerie (
  id bigint generated by default as identity primary key,
  employe_id bigint references public.employes(id) on delete set null,
  date_jour date not null default current_date,
  montant_saisi numeric(14, 2) not null default 0,
  treso_theorique numeric(14, 2) not null default 0,
  ecart numeric(14, 2) generated always as (montant_saisi - treso_theorique) stored,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table public.archives_rh (
  id bigint generated by default as identity primary key,
  periode_id bigint not null references public.periodes_comptables(id) on delete cascade,
  employe_id bigint references public.employes(id) on delete set null,
  employe_nom text not null,
  ca_ventes numeric(14, 2) not null default 0,
  prime numeric(14, 2) not null default 0,
  total_paye numeric(14, 2) not null default 0,
  created_at timestamptz not null default now(),
  unique (periode_id, employe_id)
);

create table public.inscriptions_permis (
  id bigint generated by default as identity primary key,
  type_permis text not null check (type_permis in ('Balais', 'Voiture', 'Moto')),
  candidat text not null,
  hibou text,
  notes text,
  hibou_envoye boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.permis (
  id bigint generated by default as identity primary key,
  type_permis text not null check (type_permis in ('Balais', 'Voiture', 'Moto')),
  candidat text not null,
  date_passage date not null default current_date,
  hibou text,
  resultat text,
  essais integer not null default 1 check (essais >= 0),
  retrait text not null default 'NON' check (retrait in ('NON', 'OUI')),
  client_id bigint references public.clients(id) on delete set null,
  statut text check (statut in ('validé', 'retiré', 'interdit')),
  document_sell boolean not null default false,
  valide_par bigint references public.employes(id) on delete set null,
  retire_par bigint references public.employes(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.mots_de_passe_direction (
  id bigint generated by default as identity primary key,
  mot_de_passe_hash text not null,
  est_maitre boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.fabrications (
  id bigint generated by default as identity primary key,
  employe_id bigint references public.employes(id) on delete set null,
  employe_nom text not null,
  produit_id bigint references public.catalogue(id) on delete set null,
  produit_nom text not null,
  nombre_crafts integer not null check (nombre_crafts > 0),
  quantite_produite integer not null check (quantite_produite > 0),
  cout_ingredients numeric(14, 2) not null default 0,
  cout_craft_total numeric(14, 2) not null default 0,
  cout_total numeric(14, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table public.fabrications_ingredients (
  id bigint generated by default as identity primary key,
  fabrication_id bigint not null references public.fabrications(id) on delete cascade,
  ingredient_id bigint references public.catalogue(id) on delete set null,
  ingredient_nom text not null,
  quantite_consommee integer not null check (quantite_consommee > 0),
  cout_unitaire numeric(14, 2) not null default 0,
  cout_total numeric(14, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table public.commandes_journal (
  id bigint generated by default as identity primary key,
  commande_id bigint references public.commandes(id) on delete set null,
  commande_reference bigint not null,
  employe_id bigint references public.employes(id) on delete set null,
  employe_nom text not null,
  action text not null check (action in (
    'Annulation', 'Restauration', 'Retour arrière', 'Suppression',
    'Préparation terminée', 'Livraison'
  )),
  statut_avant text,
  statut_apres text,
  commande_snapshot jsonb not null,
  created_at timestamptz not null default now()
);

create table public.journal_actions (
  id bigint generated by default as identity primary key,
  employe_id bigint references public.employes(id) on delete set null,
  employe_nom text not null,
  action text not null,
  entite_type text not null,
  entite_id text,
  libelle text not null,
  element text,
  client_id bigint references public.clients(id) on delete set null,
  etat_avant jsonb,
  etat_apres jsonb,
  metadata jsonb not null default '{}'::jsonb,
  resultat text not null default 'Réussite' check (resultat in ('Réussite', 'Refus')),
  created_at timestamptz not null default now()
);

create table public.client_permits (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  type text not null check (type in ('broomstick', 'motorcycle', 'car')),
  status text not null check (status in ('pending', 'accepted', 'refused', 'cancelled', 'sold')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, type)
);

-- Indexes

create unique index une_seule_periode_comptable_ouverte_idx
  on public.periodes_comptables (statut)
  where statut = 'ouverte';

create index transactions_date_idx on public.transactions (date_transaction desc);

create index transactions_periode_idx on public.transactions (periode_id, created_at desc);

create index transactions_vendeur_idx on public.transactions (vendeur_id);

create index transactions_article_idx on public.transactions (article_id);

create index commandes_livraison_idx on public.commandes (date_livraison);

create index commandes_client_idx on public.commandes (client_id);

create index commandes_employe_idx on public.commandes (employe_id);

create index lignes_commandes_article_idx on public.lignes_commandes (article_id);

create index registre_tickets_client_date_idx on public.registre_tickets (client_id, created_at desc);

create index archives_rh_employe_idx on public.archives_rh (employe_id);

create index inscriptions_permis_type_idx on public.inscriptions_permis (type_permis, id);

create index permis_type_candidat_idx on public.permis (type_permis, candidat);

create index clients_hibou_idx on public.clients (hibou) where hibou is not null;

create index registre_tickets_session_idx on public.registre_tickets (client_id, date_session);

create unique index permis_client_type_idx
  on public.permis (client_id, type_permis)
  where client_id is not null;

create index journal_actions_date_idx on public.journal_actions (created_at desc);

create index journal_actions_employe_idx on public.journal_actions (employe_id, created_at desc);

create index journal_actions_entite_idx on public.journal_actions (entite_type, entite_id);

create index journal_actions_client_idx on public.journal_actions (client_id, created_at desc);

create index journal_actions_element_idx on public.journal_actions (element, created_at desc);

-- Views

create view public.transactions_courantes
with (security_invoker = true) as
select transaction.*
from public.transactions transaction
join public.periodes_comptables periode on periode.id = transaction.periode_id
where periode.statut = 'ouverte';

create view public.periode_comptable_courante
with (security_invoker = true) as
select
  periode.*,
  (current_date - periode.date_debut)::integer as jours_ouverts,
  greatest(14 - (current_date - periode.date_debut), 0)::integer as jours_avant_cloture,
  current_date - periode.date_debut >= 14 as cloture_recommandee
from public.periodes_comptables periode
where periode.statut = 'ouverte';

create view public.performances_employes
with (security_invoker = true) as
select
  employe.id as employe_id,
  employe.nom_prenom,
  employe.grade,
  employe.prime_actuelle,
  coalesce(sum(transaction.prix_total) filter (where transaction.type_transaction = 'Vente'), 0)::numeric(14, 2) as ca_realise,
  coalesce(sum(transaction.benefice_total) filter (where transaction.type_transaction = 'Vente'), 0)::numeric(14, 2) as benefice_realise,
  count(transaction.id) filter (where transaction.type_transaction = 'Vente')::integer as nombre_lignes_vente,
  coalesce(sum(transaction.quantite) filter (where transaction.type_transaction = 'Vente'), 0)::integer as articles_vendus
from public.employes employe
left join public.transactions_courantes transaction on transaction.vendeur_id = employe.id
where employe.actif
group by employe.id, employe.nom_prenom, employe.grade, employe.prime_actuelle;

create view public.historique_comptable
with (security_invoker = true) as
select periode.*
from public.periodes_comptables periode
where periode.statut = 'clôturée'
order by periode.date_fin desc;

create view public.employes_actifs
with (security_invoker = true) as
select * from public.employes where actif;

create view public.catalogue_actif with (security_invoker = true) as
select * from public.catalogue where actif;

create view public.clients_actifs
with (security_invoker = true) as
select * from public.clients where actif;

create view public.commandes_en_cours
with (security_invoker = true) as
select * from public.commandes where statut_livraison <> 'Livré';

create or replace view public.tresorerie_courante
with (security_invoker = true) as
select coalesce(sum(prix_total), 0)::numeric(14, 2) as montant_theorique
from public.transactions_courantes;

-- Functions

create or replace function public.mettre_a_jour_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.periode_comptable_ouverte_id()
returns bigint
language plpgsql
stable
set search_path = ''
as $$
declare
  periode_id bigint;
begin
  select id into periode_id
  from public.periodes_comptables
  where statut = 'ouverte';

  if periode_id is null then
    raise exception 'Aucune période comptable ouverte';
  end if;
  return periode_id;
end;
$$;

create or replace function public.session_jeu(p_moment timestamptz default now())
returns date
language plpgsql
stable
set search_path = ''
as $$
declare
  moment_local timestamp := p_moment at time zone 'Europe/Madrid';
begin
  if moment_local::time >= time '15:00' then
    return moment_local::date;
  end if;
  return moment_local::date - 1;
end;
$$;

create or replace function public.preparer_transaction()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  debut_periode date;
begin
  new.periode_id := coalesce(new.periode_id, public.periode_comptable_ouverte_id());
  select date_debut into debut_periode
  from public.periodes_comptables
  where id = new.periode_id and statut = 'ouverte';
  if debut_periode is null then
    raise exception 'La transaction doit appartenir à une période ouverte';
  end if;
  if new.date_transaction < debut_periode then
    raise exception 'La date de transaction précède la période comptable ouverte';
  end if;

  if new.vendeur_id is not null then
    select nom_prenom into new.vendeur_nom from public.employes where id = new.vendeur_id;
  end if;
  if new.article_id is not null then
    select article into new.article_nom from public.catalogue where id = new.article_id;
  end if;
  return new;
end;
$$;

create or replace function public.preparer_commande()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.client_id is not null then
    select nom_prenom into new.client_nom from public.clients where id = new.client_id;
  end if;
  if new.employe_id is not null then
    select nom_prenom into new.employe_nom from public.employes where id = new.employe_id;
  end if;
  return new;
end;
$$;

create or replace function public.preparer_ligne_commande()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  select article into new.article_nom from public.catalogue where id = new.article_id;
  if new.article_nom is null then
    raise exception 'Article % introuvable', new.article_id;
  end if;
  return new;
end;
$$;

create or replace function public.incrementer_stock(p_article_id bigint, p_quantite integer)
returns void
language plpgsql
set search_path = ''
as $$
begin
  if p_quantite <= 0 then
    raise exception 'La quantité à ajouter doit être strictement positive';
  end if;

  insert into public.stocks (article_id, quantite)
  values (p_article_id, p_quantite)
  on conflict (article_id) do update
  set quantite = public.stocks.quantite + excluded.quantite,
      updated_at = now();
end;
$$;

create or replace function public.decrementer_stock(p_article_id bigint, p_quantite integer)
returns void
language plpgsql
set search_path = ''
as $$
declare
  quantite_disponible integer;
begin
  if p_quantite <= 0 then
    raise exception 'La quantité à retirer doit être strictement positive';
  end if;

  select stock.quantite
  into quantite_disponible
  from public.stocks stock
  where stock.article_id = p_article_id
  for update;

  if quantite_disponible is null then
    raise exception 'Aucun stock trouvé pour l''article %', p_article_id;
  end if;

  if quantite_disponible < p_quantite then
    raise exception 'Stock insuffisant pour l''article % : % disponible(s), % demandé(s)',
      p_article_id, quantite_disponible, p_quantite;
  end if;

  update public.stocks
  set quantite = quantite - p_quantite,
      updated_at = now()
  where article_id = p_article_id;
end;
$$;

create or replace function public.cout_revient_article(
  p_article_id bigint,
  p_articles_visites bigint[] default '{}'::bigint[]
)
returns numeric
language plpgsql
stable
set search_path = ''
as $$
declare
  article public.catalogue%rowtype;
  ingredient record;
  cout numeric := 0;
begin
  if p_article_id = any(p_articles_visites) then
    raise exception 'Cycle détecté dans la recette de l''article %', p_article_id;
  end if;

  select * into article from public.catalogue where id = p_article_id;
  if not found then
    raise exception 'Article % introuvable', p_article_id;
  end if;

  if article.prix_achat > 0 then
    return article.prix_achat;
  end if;

  cout := article.cout_craft_po;
  for ingredient in
    select recette.ingredient_id, recette.quantite_requise, recette.quantite_produite
    from public.recettes_craft recette
    where recette.produit_id = p_article_id
  loop
    cout := cout + public.cout_revient_article(
      ingredient.ingredient_id,
      array_append(p_articles_visites, p_article_id)
    ) * ingredient.quantite_requise / ingredient.quantite_produite;
  end loop;

  return round(cout, 2);
end;
$$;

create or replace function public.ecrire_journal_action(
  p_employe_id bigint,
  p_action text,
  p_entite_type text,
  p_entite_id text,
  p_libelle text,
  p_etat_avant jsonb default null,
  p_etat_apres jsonb default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_employe_nom text;
begin
  select nom_prenom into v_employe_nom from public.employes where id = p_employe_id;
  if v_employe_nom is null then raise exception 'Employé introuvable pour le journal'; end if;
  insert into public.journal_actions (
    employe_id, employe_nom, action, entite_type, entite_id, libelle,
    etat_avant, etat_apres, metadata
  ) values (
    p_employe_id, v_employe_nom, p_action, p_entite_type, p_entite_id,
    p_libelle, p_etat_avant, p_etat_apres, coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function public.journaliser_action_client(
  p_employe_id bigint,
  p_action text,
  p_entite_type text,
  p_entite_id text,
  p_element text,
  p_client_id bigint,
  p_avant jsonb,
  p_apres jsonb,
  p_metadata jsonb default '{}'::jsonb
)
returns void language plpgsql security definer set search_path = '' as $$
declare v_employe_nom text;
begin
  select nom_prenom into v_employe_nom from public.employes where id = p_employe_id and actif;
  if v_employe_nom is null then raise exception 'Employé introuvable ou inactif'; end if;
  insert into public.journal_actions (
    employe_id, employe_nom, action, entite_type, entite_id, libelle,
    element, client_id, etat_avant, etat_apres, metadata
  ) values (
    p_employe_id, v_employe_nom, p_action, p_entite_type, p_entite_id,
    p_element, p_element, p_client_id, p_avant, p_apres, coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function public.enregistrer_vente(
  p_vendeur_id bigint,
  p_lignes jsonb,
  p_remise_pourcent numeric default 0,
  p_type_transaction text default 'Vente'
)
returns numeric
language plpgsql
set search_path = ''
as $$
declare
  ligne record;
  article public.catalogue%rowtype;
  total_ligne numeric;
  cout_ligne numeric;
  total_vente numeric := 0;
begin
  if not exists (select 1 from public.employes where id = p_vendeur_id and actif) then
    raise exception 'Employé % introuvable ou inactif', p_vendeur_id;
  end if;
  if jsonb_typeof(p_lignes) <> 'array' or jsonb_array_length(p_lignes) = 0 then
    raise exception 'La vente doit contenir au moins une ligne';
  end if;
  if p_remise_pourcent < 0 or p_remise_pourcent > 100 then raise exception 'Remise invalide'; end if;
  if p_type_transaction not in ('Vente', 'Vente Employé') then raise exception 'Type de vente invalide'; end if;

  for ligne in
    select (element->>'article_id')::bigint article_id, (element->>'quantite')::integer quantite
    from jsonb_array_elements(p_lignes) element
    order by (element->>'article_id')::bigint
  loop
    if ligne.quantite is null or ligne.quantite <= 0 then raise exception 'Quantité de vente invalide'; end if;
    select * into article from public.catalogue where id = ligne.article_id and actif;
    if not found or article.prix_vente <= 0 then raise exception 'Article % non vendable', ligne.article_id; end if;

    -- Le supplément boussole est une majoration tarifaire et non un article physique.
    if lower(article.article) <> lower('Supplément boussole') then
      perform public.decrementer_stock(article.id, ligne.quantite);
    end if;

    total_ligne := round(article.prix_vente * ligne.quantite * (100 - p_remise_pourcent) / 100);
    cout_ligne := public.cout_revient_article(article.id) * ligne.quantite;
    insert into public.transactions (vendeur_id, article_id, quantite, prix_unitaire, prix_total, benefice_total, type_transaction)
    values (p_vendeur_id, article.id, ligne.quantite, article.prix_vente, total_ligne, total_ligne - cout_ligne, p_type_transaction);
    total_vente := total_vente + total_ligne;
  end loop;
  return total_vente;
end;
$$;

create or replace function public.enregistrer_rachat(p_employe_id bigint, p_lignes jsonb)
returns numeric
language plpgsql
set search_path = ''
as $$
declare
  ligne record;
  article public.catalogue%rowtype;
  cout_ligne numeric;
  total_rachat numeric := 0;
begin
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then
    raise exception 'Employé % introuvable ou inactif', p_employe_id;
  end if;
  if jsonb_typeof(p_lignes) <> 'array' or jsonb_array_length(p_lignes) = 0 then
    raise exception 'Le rachat doit contenir au moins une ligne';
  end if;

  for ligne in
    select (element->>'article_id')::bigint as article_id,
           (element->>'quantite')::integer as quantite
    from jsonb_array_elements(p_lignes) element
    order by (element->>'article_id')::bigint
  loop
    if ligne.quantite is null or ligne.quantite <= 0 then
      raise exception 'Chaque quantité rachetée doit être strictement positive';
    end if;
    select * into article from public.catalogue where id = ligne.article_id and actif;
    if not found then raise exception 'Article % introuvable ou inactif', ligne.article_id; end if;

    cout_ligne := article.prix_achat * ligne.quantite;
    insert into public.transactions (
      vendeur_id, article_id, quantite, prix_unitaire, prix_total,
      benefice_total, type_transaction
    ) values (
      p_employe_id, article.id, ligne.quantite, article.prix_achat,
      -cout_ligne, -cout_ligne, 'Achat'
    );
    perform public.incrementer_stock(article.id, ligne.quantite);
    total_rachat := total_rachat + cout_ligne;
  end loop;

  return total_rachat;
end;
$$;

create or replace function public.enregistrer_frais(
  p_employe_id bigint,
  p_motif text,
  p_montant numeric
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  transaction_id bigint;
begin
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then
    raise exception 'Employé % introuvable ou inactif', p_employe_id;
  end if;
  if nullif(trim(p_motif), '') is null then raise exception 'Le motif est obligatoire'; end if;
  if p_montant <= 0 then raise exception 'Le montant doit être strictement positif'; end if;

  insert into public.transactions (
    vendeur_id, quantite, prix_unitaire, prix_total, benefice_total, type_transaction
  ) values (
    p_employe_id, 1, -p_montant, -p_montant, -p_montant, 'Frais : ' || trim(p_motif)
  ) returning id into transaction_id;
  return transaction_id;
end;
$$;

create or replace function public.enregistrer_achat_employe(p_employe_id bigint, p_lignes jsonb)
returns numeric language plpgsql set search_path = '' as $$
declare ligne record; article public.catalogue%rowtype; prix numeric; total numeric := 0;
begin
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then raise exception 'Employé invalide'; end if;
  if jsonb_typeof(p_lignes) <> 'array' or jsonb_array_length(p_lignes) = 0 then raise exception 'Achat employé vide'; end if;
  for ligne in select (element->>'article_id')::bigint article_id, (element->>'quantite')::integer quantite from jsonb_array_elements(p_lignes) element order by 1
  loop
    if ligne.quantite <= 0 then raise exception 'Quantité invalide'; end if;
    select * into article from public.catalogue where id = ligne.article_id and actif;
    if not found then raise exception 'Article introuvable'; end if;
    prix := public.cout_revient_article(article.id);
    perform public.decrementer_stock(article.id, ligne.quantite);
    insert into public.transactions (vendeur_id, article_id, quantite, prix_unitaire, prix_total, benefice_total, type_transaction)
    values (p_employe_id, article.id, ligne.quantite, prix, prix * ligne.quantite, 0, 'Vente Employé');
    total := total + prix * ligne.quantite;
  end loop;
  return total;
end;
$$;

create or replace function public.enregistrer_panier(
  p_vendeur_id bigint,
  p_lignes jsonb,
  p_client_ticket_id bigint default null,
  p_retraits_permis jsonb default '[]'::jsonb
)
returns numeric language plpgsql security definer set search_path = '' as $$
declare
  session_date date := public.session_jeu();
  ticket_quantite integer;
  ticket_deja integer := 0;
  retrait record;
  permit public.client_permits%rowtype;
  article_type text;
  article_permit_type text;
  expected_permits integer;
  total numeric;
begin
  if not exists (select 1 from public.employes where id = p_vendeur_id and actif) then raise exception 'Employé introuvable ou inactif'; end if;
  if jsonb_typeof(p_lignes) <> 'array' or jsonb_array_length(p_lignes) = 0 then raise exception 'Le panier est vide'; end if;

  select coalesce(sum((element->>'quantite')::integer), 0) into ticket_quantite
  from jsonb_array_elements(p_lignes) element
  join public.catalogue article on article.id = (element->>'article_id')::bigint
  where article.type_article = 'ticket';

  if ticket_quantite > 0 then
    if ticket_quantite > 2 then raise exception 'Deux tickets maximum par client et par session'; end if;
    if p_client_ticket_id is null then raise exception 'Un client actif est obligatoire pour les tickets'; end if;
    perform pg_advisory_xact_lock(hashtextextended('ticket:' || p_client_ticket_id || ':' || session_date, 0));
    select case when ticket_session = session_date then tickets_retires else 0 end into ticket_deja
    from public.clients where id = p_client_ticket_id and actif for update;
    if not found then raise exception 'Un client actif est obligatoire pour les tickets'; end if;
    if ticket_deja + ticket_quantite > 2 then raise exception 'Quota de tickets insuffisant pour cette session'; end if;
  elsif p_client_ticket_id is not null then raise exception 'Aucun ticket présent dans le panier';
  end if;

  select coalesce(sum((element->>'quantite')::integer), 0) into expected_permits
  from jsonb_array_elements(p_lignes) element
  join public.catalogue article on article.id = (element->>'article_id')::bigint
  where article.type_article = 'document_permis';
  if jsonb_typeof(p_retraits_permis) <> 'array' or jsonb_array_length(p_retraits_permis) <> expected_permits then
    raise exception 'Chaque document de permis doit avoir un bénéficiaire';
  end if;
  if (select count(distinct (element->>'permit_id')) from jsonb_array_elements(p_retraits_permis) element) <> expected_permits then
    raise exception 'Un même dossier de permis ne peut être vendu qu’une fois';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_lignes) element
    join public.catalogue article on article.id = (element->>'article_id')::bigint
    where article.type_article = 'document_permis'
      and (element->>'quantite')::integer > 1
  ) then raise exception 'Un seul permis de chaque type peut être vendu par panier';
  end if;
  if exists (
    select 1
    from (
      select (element->>'article_id')::bigint article_id, (element->>'quantite')::integer quantite
      from jsonb_array_elements(p_lignes) element
      join public.catalogue article on article.id = (element->>'article_id')::bigint
      where article.type_article = 'document_permis'
    ) basket_permits
    full join (
      select (element->>'article_id')::bigint article_id, count(*)::integer quantite
      from jsonb_array_elements(p_retraits_permis) element
      group by 1
    ) assigned_permits using (article_id)
    where coalesce(basket_permits.quantite, 0) <> coalesce(assigned_permits.quantite, 0)
  ) then raise exception 'Chaque type de permis doit avoir exactement un bénéficiaire';
  end if;

  for retrait in
    select (element->>'article_id')::bigint article_id, (element->>'permit_id')::bigint permit_id
    from jsonb_array_elements(p_retraits_permis) element
  loop
    select type_article,
      case type_permis when 'Balais' then 'broomstick' when 'Moto' then 'motorcycle' when 'Voiture' then 'car' end
    into article_type, article_permit_type from public.catalogue where id = retrait.article_id;
    if article_type <> 'document_permis' then raise exception 'Article non lié à un permis'; end if;
    select * into permit from public.client_permits where id = retrait.permit_id for update;
    if not found or permit.type <> article_permit_type or permit.status <> 'accepted' then
      raise exception 'Ce document de permis ne peut pas être vendu';
    end if;
  end loop;

  total := public.enregistrer_vente(p_vendeur_id, p_lignes, 0, 'Vente');

  if ticket_quantite > 0 then
    update public.clients set tickets_retires = ticket_deja + ticket_quantite,
      ticket_session = session_date, updated_by = p_vendeur_id where id = p_client_ticket_id;
    perform public.journaliser_action_client(p_vendeur_id, 'withdraw_ticket', 'client', p_client_ticket_id::text,
      'ticket', p_client_ticket_id,
      jsonb_build_object('session', session_date, 'tickets_retires', ticket_deja),
      jsonb_build_object('session', session_date, 'tickets_retires', ticket_deja + ticket_quantite));
  end if;

  for retrait in
    select (element->>'permit_id')::bigint permit_id from jsonb_array_elements(p_retraits_permis) element
  loop
    select * into permit from public.client_permits where id = retrait.permit_id;
    update public.client_permits set status = 'sold' where id = permit.id;
    perform public.journaliser_action_client(p_vendeur_id, 'sell', 'client_permit', permit.id::text,
      'permit_' || permit.type, permit.client_id,
      jsonb_build_object('status', 'accepted'), jsonb_build_object('status', 'sold'));
  end loop;
  return total;
end;
$$;

create or replace function public.enregistrer_panier_employe(
  p_employe_id bigint,
  p_lignes jsonb,
  p_client_ticket_id bigint default null
)
returns numeric
language plpgsql
security definer
set search_path = ''
as $$
declare
  session_date date := public.session_jeu();
  ticket_quantite integer;
  ticket_deja integer := 0;
  total numeric;
begin
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then
    raise exception 'Employé introuvable ou inactif';
  end if;
  if jsonb_typeof(p_lignes) <> 'array' or jsonb_array_length(p_lignes) = 0 then
    raise exception 'Le panier est vide';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_lignes) element
    join public.catalogue article on article.id = (element->>'article_id')::bigint
    where article.type_article = 'document_permis'
  ) then
    raise exception 'Les documents de permis ne sont pas disponibles en achat employé';
  end if;

  select coalesce(sum((element->>'quantite')::integer), 0)
  into ticket_quantite
  from jsonb_array_elements(p_lignes) element
  join public.catalogue article on article.id = (element->>'article_id')::bigint
  where article.type_article = 'ticket';

  if ticket_quantite > 0 then
    if ticket_quantite > 2 then raise exception 'Deux tickets maximum par client et par session'; end if;
    if p_client_ticket_id is null then raise exception 'Un client actif est obligatoire pour les tickets'; end if;
    perform pg_advisory_xact_lock(hashtextextended('ticket:' || p_client_ticket_id || ':' || session_date, 0));
    select case when ticket_session = session_date then tickets_retires else 0 end
    into ticket_deja
    from public.clients
    where id = p_client_ticket_id and actif
    for update;
    if not found then raise exception 'Un client actif est obligatoire pour les tickets'; end if;
    if ticket_deja + ticket_quantite > 2 then raise exception 'Quota de tickets insuffisant pour cette session'; end if;
  elsif p_client_ticket_id is not null then
    raise exception 'Aucun ticket présent dans le panier';
  end if;

  total := public.enregistrer_achat_employe(p_employe_id, p_lignes);

  if ticket_quantite > 0 then
    update public.clients
    set tickets_retires = ticket_deja + ticket_quantite,
        ticket_session = session_date,
        updated_by = p_employe_id
    where id = p_client_ticket_id;
    perform public.journaliser_action_client(
      p_employe_id, 'withdraw_ticket', 'client', p_client_ticket_id::text,
      'ticket', p_client_ticket_id,
      jsonb_build_object('session', session_date, 'tickets_retires', ticket_deja),
      jsonb_build_object('session', session_date, 'tickets_retires', ticket_deja + ticket_quantite)
    );
  end if;

  return total;
end;
$$;

create or replace function public.fabriquer_article(p_employe_id bigint, p_article_id bigint, p_nombre_crafts integer)
returns integer
language plpgsql
set search_path = ''
as $$
declare
  v_produit public.catalogue%rowtype;
  v_employe_nom text;
  v_ingredient record;
  v_quantite_produite integer;
  v_fabrication_id bigint;
  v_cout_ingredients numeric := 0;
  v_cout_ligne numeric;
begin
  if p_nombre_crafts <= 0 then raise exception 'Le nombre de crafts doit être positif'; end if;

  select employe.nom_prenom
  into v_employe_nom
  from public.employes employe
  where employe.id = p_employe_id and employe.actif;
  if v_employe_nom is null then raise exception 'Employé introuvable ou inactif'; end if;

  select catalogue.*
  into v_produit
  from public.catalogue catalogue
  where catalogue.id = p_article_id and catalogue.actif;
  if not found then raise exception 'Produit introuvable ou inactif'; end if;

  select recette.quantite_produite * p_nombre_crafts
  into v_quantite_produite
  from public.recettes_craft recette
  where recette.produit_id = p_article_id
  order by recette.id
  limit 1;
  if v_quantite_produite is null then raise exception 'Aucune recette trouvée'; end if;

  insert into public.fabrications (
    employe_id, employe_nom, produit_id, produit_nom, nombre_crafts,
    quantite_produite, cout_craft_total
  ) values (
    p_employe_id, v_employe_nom, v_produit.id, v_produit.article, p_nombre_crafts,
    v_quantite_produite, v_produit.cout_craft_po * p_nombre_crafts
  ) returning id into v_fabrication_id;

  for v_ingredient in
    select recette.ingredient_id, catalogue.article,
      recette.quantite_requise * p_nombre_crafts as quantite
    from public.recettes_craft recette
    join public.catalogue catalogue on catalogue.id = recette.ingredient_id
    where recette.produit_id = p_article_id
    order by recette.ingredient_id
  loop
    perform public.decrementer_stock(v_ingredient.ingredient_id, v_ingredient.quantite);
    v_cout_ligne := public.cout_revient_article(v_ingredient.ingredient_id) * v_ingredient.quantite;
    v_cout_ingredients := v_cout_ingredients + v_cout_ligne;
    insert into public.fabrications_ingredients (
      fabrication_id, ingredient_id, ingredient_nom, quantite_consommee,
      cout_unitaire, cout_total
    ) values (
      v_fabrication_id, v_ingredient.ingredient_id, v_ingredient.article,
      v_ingredient.quantite, public.cout_revient_article(v_ingredient.ingredient_id),
      v_cout_ligne
    );
  end loop;

  perform public.incrementer_stock(p_article_id, v_quantite_produite);
  update public.fabrications
  set cout_ingredients = v_cout_ingredients,
    cout_total = v_cout_ingredients + public.fabrications.cout_craft_total
  where public.fabrications.id = v_fabrication_id;

  insert into public.transactions (
    vendeur_id, article_id, quantite, prix_total, benefice_total, type_transaction
  ) values (
    p_employe_id, p_article_id, v_quantite_produite,
    -(v_produit.cout_craft_po * p_nombre_crafts),
    -(v_produit.cout_craft_po * p_nombre_crafts), 'Frais de Craft'
  );

  return v_quantite_produite;
end;
$$;

create or replace function public.recalculer_total_commande()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  id_commande bigint := coalesce(new.commande_id, old.commande_id);
begin
  update public.commandes
  set prix_total = coalesce((
    select sum(ligne.quantite * ligne.prix_unitaire)
    from public.lignes_commandes ligne
    where ligne.commande_id = id_commande
  ), 0)
  where id = id_commande;
  return coalesce(new, old);
end;
$$;

create or replace function public.creer_commande(
  p_client_id bigint,
  p_employe_id bigint,
  p_date_livraison date,
  p_lignes jsonb,
  p_contenu text default null
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  commande_id bigint;
  ligne record;
  prix_article numeric;
begin
  if jsonb_typeof(p_lignes) <> 'array' or jsonb_array_length(p_lignes) = 0 then
    raise exception 'La commande doit contenir au moins une ligne';
  end if;
  if not exists (select 1 from public.clients where id = p_client_id and actif) then
    raise exception 'Client % introuvable ou inactif', p_client_id;
  end if;
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then
    raise exception 'Employé % introuvable ou inactif', p_employe_id;
  end if;

  insert into public.commandes (client_id, employe_id, date_livraison, contenu)
  values (p_client_id, p_employe_id, p_date_livraison, nullif(trim(p_contenu), ''))
  returning id into commande_id;

  for ligne in
    select (element->>'article_id')::bigint as article_id,
           (element->>'quantite')::integer as quantite,
           nullif(element->>'prix_unitaire', '')::numeric as prix_unitaire
    from jsonb_array_elements(p_lignes) element
  loop
    if ligne.quantite is null or ligne.quantite <= 0 then
      raise exception 'Chaque quantité commandée doit être strictement positive';
    end if;
    select catalogue.prix_vente into prix_article
    from public.catalogue catalogue
    where catalogue.id = ligne.article_id and catalogue.actif;
    if not found then raise exception 'Article % introuvable ou inactif', ligne.article_id; end if;

    insert into public.lignes_commandes (commande_id, article_id, quantite, prix_unitaire)
    values (commande_id, ligne.article_id, ligne.quantite, coalesce(ligne.prix_unitaire, prix_article));
  end loop;
  return commande_id;
end;
$$;

create or replace function public.changer_statut_commande(p_commande_id bigint, p_nouveau_statut text)
returns void
language plpgsql
set search_path = ''
as $$
declare
  statut_actuel text;
begin
  select statut_livraison into statut_actuel
  from public.commandes where id = p_commande_id for update;
  if statut_actuel is null then raise exception 'Commande introuvable'; end if;
  if not (
    (statut_actuel = 'En préparation' and p_nouveau_statut = 'Prêt')
    or (statut_actuel = 'Prêt' and p_nouveau_statut = 'Livré')
  ) then
    raise exception 'Transition de commande invalide';
  end if;
  update public.commandes set
    statut_livraison = p_nouveau_statut,
    date_pret = case when p_nouveau_statut = 'Prêt' then current_date else date_pret end
  where id = p_commande_id;
end;
$$;

create or replace function public.gerer_commande(
  p_commande_id bigint,
  p_employe_id bigint,
  p_action text
)
returns void
language plpgsql
set search_path = ''
as $$
declare
  commande public.commandes%rowtype;
  employe_nom text;
  prochain_statut text;
  snapshot jsonb;
begin
  select nom_prenom into employe_nom
  from public.employes where id = p_employe_id and actif;
  if employe_nom is null then raise exception 'Employé introuvable ou inactif'; end if;

  select * into commande from public.commandes where id = p_commande_id for update;
  if not found then raise exception 'Commande introuvable'; end if;

  snapshot := to_jsonb(commande) || jsonb_build_object(
    'lignes', coalesce((select jsonb_agg(to_jsonb(ligne) order by ligne.id)
      from public.lignes_commandes ligne where ligne.commande_id = commande.id), '[]'::jsonb)
  );

  if p_action = 'Préparation terminée' then
    if commande.statut_livraison <> 'En préparation' then raise exception 'Transition de commande invalide'; end if;
    prochain_statut := 'Prêt';
    update public.commandes set statut_livraison = prochain_statut, date_pret = current_date where id = commande.id;
  elsif p_action = 'Livraison' then
    if commande.statut_livraison <> 'Prêt' then raise exception 'Transition de commande invalide'; end if;
    prochain_statut := 'Livré';
    update public.commandes set statut_livraison = prochain_statut where id = commande.id;
  elsif p_action = 'Annulation' then
    if commande.statut_livraison in ('Livré', 'Annulée') then raise exception 'Cette commande ne peut plus être annulée'; end if;
    prochain_statut := 'Annulée';
    update public.commandes set statut_avant_annulation = commande.statut_livraison,
      statut_livraison = prochain_statut where id = commande.id;
  elsif p_action = 'Restauration' then
    if commande.statut_livraison <> 'Annulée' then raise exception 'Seule une commande annulée peut être restaurée'; end if;
    prochain_statut := coalesce(commande.statut_avant_annulation, 'En préparation');
    update public.commandes set statut_livraison = prochain_statut,
      statut_avant_annulation = null where id = commande.id;
  elsif p_action = 'Retour arrière' then
    prochain_statut := case commande.statut_livraison
      when 'Prêt' then 'En préparation'
      when 'Livré' then 'Prêt'
      else null
    end;
    if prochain_statut is null then raise exception 'Aucun état précédent disponible'; end if;
    update public.commandes set statut_livraison = prochain_statut,
      date_pret = case when prochain_statut = 'En préparation' then null else date_pret end
    where id = commande.id;
  elsif p_action = 'Suppression' then
    if commande.statut_livraison <> 'Annulée' then raise exception 'Une commande doit être annulée avant sa suppression'; end if;
    prochain_statut := null;
  else
    raise exception 'Action de commande invalide';
  end if;

  insert into public.commandes_journal (
    commande_id, commande_reference, employe_id, employe_nom, action,
    statut_avant, statut_apres, commande_snapshot
  ) values (
    commande.id, commande.id, p_employe_id, employe_nom, p_action,
    commande.statut_livraison, prochain_statut, snapshot
  );

  if p_action = 'Suppression' then delete from public.commandes where id = commande.id; end if;
end;
$$;

create or replace function public.valider_passage_permis(p_permis_id bigint, p_employe_id bigint, p_statut text)
returns void language plpgsql set search_path = '' as $$
begin
  if p_statut not in ('validé', 'interdit') then raise exception 'Statut de permis invalide'; end if;
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then raise exception 'Employé invalide'; end if;
  update public.permis set statut = p_statut, valide_par = p_employe_id,
    resultat = case when p_statut = 'validé' then 'Admis' else 'Interdit' end
  where id = p_permis_id and statut is null;
  if not found then raise exception 'Permis introuvable ou déjà traité'; end if;
end;
$$;

create or replace function public.enregistrer_client_permit(
  p_permit_id bigint,
  p_client_id bigint,
  p_type text,
  p_status text,
  p_employe_id bigint
)
returns bigint language plpgsql security definer set search_path = '' as $$
declare permit public.client_permits%rowtype; permit_id bigint; before_state jsonb;
begin
  if p_type not in ('broomstick', 'motorcycle', 'car') then raise exception 'Type de permis invalide'; end if;
  if p_status not in ('pending', 'accepted', 'refused', 'cancelled') then raise exception 'État de permis invalide'; end if;
  if not exists (select 1 from public.clients where id = p_client_id and actif) then raise exception 'Client introuvable ou archivé'; end if;
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then raise exception 'Employé introuvable ou inactif'; end if;

  if p_permit_id is null then
    insert into public.client_permits (client_id, type, status)
    values (p_client_id, p_type, p_status) returning id into permit_id;
    perform public.journaliser_action_client(p_employe_id, 'create', 'client_permit', permit_id::text,
      'permit_' || p_type, p_client_id, null, jsonb_build_object('status', p_status));
  else
    select * into permit from public.client_permits where id = p_permit_id for update;
    if not found then raise exception 'Dossier de permis introuvable'; end if;
    if permit.status = 'sold' then raise exception 'Un permis vendu ne peut pas être modifié'; end if;
    before_state := jsonb_build_object('client_id', permit.client_id, 'type', permit.type, 'status', permit.status);
    update public.client_permits set client_id = p_client_id, type = p_type, status = p_status
    where id = permit.id returning id into permit_id;
    perform public.journaliser_action_client(p_employe_id, 'update_status', 'client_permit', permit_id::text,
      'permit_' || p_type, p_client_id, before_state,
      jsonb_build_object('client_id', p_client_id, 'type', p_type, 'status', p_status));
  end if;
  return permit_id;
exception when unique_violation then
  raise exception 'Ce client possède déjà un dossier pour ce type de permis';
end;
$$;

create or replace function public.creer_client(
  p_nom_prenom text,
  p_hibou text,
  p_employe_id bigint
)
returns bigint language plpgsql security definer set search_path = '' as $$
declare client_id bigint;
begin
  if nullif(trim(p_nom_prenom), '') is null then raise exception 'Le nom du client est obligatoire'; end if;
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then raise exception 'Employé introuvable ou inactif'; end if;
  insert into public.clients (nom_prenom, hibou, created_by, updated_by)
  values (trim(p_nom_prenom), nullif(trim(p_hibou), ''), p_employe_id, p_employe_id)
  returning id into client_id;
  perform public.journaliser_action_client(p_employe_id, 'create', 'client', client_id::text,
    'client', client_id, null,
    jsonb_build_object('nom_prenom', trim(p_nom_prenom), 'hibou', nullif(trim(p_hibou), '')));
  return client_id;
end;
$$;

create or replace function public.modifier_client(
  p_client_id bigint,
  p_nom_prenom text,
  p_hibou text,
  p_employe_id bigint
)
returns bigint language plpgsql security definer set search_path = '' as $$
declare client public.clients%rowtype; before_state jsonb;
begin
  if nullif(trim(p_nom_prenom), '') is null then raise exception 'Le nom du client est obligatoire'; end if;
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then raise exception 'Employé introuvable ou inactif'; end if;
  select * into client from public.clients where id = p_client_id and actif for update;
  if not found then raise exception 'Client introuvable ou archivé'; end if;
  before_state := jsonb_build_object('nom_prenom', client.nom_prenom, 'hibou', client.hibou);
  update public.clients set
    nom_prenom = trim(p_nom_prenom),
    hibou = nullif(trim(p_hibou), ''),
    updated_by = p_employe_id
  where id = client.id;
  perform public.journaliser_action_client(p_employe_id, 'update', 'client', client.id::text,
    'client', client.id, before_state,
    jsonb_build_object('nom_prenom', trim(p_nom_prenom), 'hibou', nullif(trim(p_hibou), '')));
  return client.id;
exception when unique_violation then
  raise exception 'Ce hibou est déjà associé à un autre client';
end;
$$;

create or replace function public.archiver_client(
  p_client_id bigint,
  p_reason text,
  p_employe_id bigint
)
returns bigint language plpgsql security definer set search_path = '' as $$
declare client public.clients%rowtype;
begin
  if p_reason not in ('departure', 'death', 'other') then raise exception 'Motif d’archivage invalide'; end if;
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then raise exception 'Employé introuvable ou inactif'; end if;
  select * into client from public.clients where id = p_client_id and actif for update;
  if not found then raise exception 'Client introuvable ou déjà archivé'; end if;
  update public.clients set actif = false, archive_reason = p_reason,
    archived_by = p_employe_id, archived_at = now(), updated_by = p_employe_id
  where id = client.id;
  perform public.journaliser_action_client(p_employe_id, 'archive', 'client', client.id::text,
    'client', client.id,
    jsonb_build_object('actif', true),
    jsonb_build_object('actif', false, 'reason', p_reason));
  return client.id;
end;
$$;

create or replace function public.enregistrer_controle_tresorerie(p_employe_id bigint, p_montant_saisi numeric, p_notes text default '')
returns bigint language plpgsql set search_path = '' as $$
declare theorique numeric; registre_id bigint;
begin
  if not exists (select 1 from public.employes where id = p_employe_id and actif) then raise exception 'Employé invalide'; end if;
  select montant_theorique into theorique from public.tresorerie_courante;
  if p_montant_saisi <> theorique and nullif(trim(p_notes), '') is null then raise exception 'Une note est obligatoire en cas d''écart'; end if;
  insert into public.registre_tresorerie (employe_id, montant_saisi, treso_theorique, notes)
  values (p_employe_id, p_montant_saisi, theorique, coalesce(trim(p_notes), '')) returning id into registre_id;
  return registre_id;
end;
$$;

create or replace function public.cloturer_periode(
  p_date_fin date default current_date,
  p_remunerations jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  periode public.periodes_comptables%rowtype;
  v_ca numeric;
  v_depenses numeric;
  v_brut numeric;
  v_taxes_calculees numeric;
  v_salaires numeric;
  v_ventes integer;
  v_achats integer;
  v_crafts integer;
  remuneration record;
begin
  select * into periode
  from public.periodes_comptables
  where statut = 'ouverte'
  for update;

  if not found then raise exception 'Aucune période comptable ouverte'; end if;
  if p_date_fin < periode.date_debut then raise exception 'Date de clôture invalide'; end if;
  if jsonb_typeof(p_remunerations) <> 'array' then
    raise exception 'Les rémunérations doivent être un tableau JSON';
  end if;
  if exists (
    select 1 from public.transactions
    where periode_id = periode.id and date_transaction > p_date_fin
  ) then
    raise exception 'Des transactions existent après la date de clôture demandée';
  end if;

  select
    coalesce(sum(prix_total) filter (where type_transaction in ('Vente', 'Vente Employé')), 0),
    coalesce(sum(abs(prix_total)) filter (
      where type_transaction = 'Achat'
         or type_transaction = 'Frais de Craft'
         or type_transaction like 'Frais : %'
    ), 0),
    count(*) filter (where type_transaction in ('Vente', 'Vente Employé')),
    count(*) filter (where type_transaction = 'Achat'),
    count(*) filter (where type_transaction = 'Frais de Craft')
  into v_ca, v_depenses, v_ventes, v_achats, v_crafts
  from public.transactions
  where periode_id = periode.id
    and date_transaction <= p_date_fin;

  v_brut := v_ca - v_depenses;
  v_taxes_calculees := round(greatest(v_brut, 0) * 0.40);
  select coalesce(sum((element->>'total_paye')::numeric), 0)
  into v_salaires
  from jsonb_array_elements(p_remunerations) element;

  update public.periodes_comptables
  set date_fin = p_date_fin,
      statut = 'clôturée',
      ca_total = v_ca,
      depenses = v_depenses,
      benefice_brut = v_brut,
      taxes = v_taxes_calculees,
      salaires_primes = v_salaires,
      benefice_net = v_brut - v_taxes_calculees,
      nombre_ventes = v_ventes,
      nombre_achats = v_achats,
      nombre_crafts = v_crafts,
      cloturee_at = now()
  where id = periode.id;

  for remuneration in
    select (element->>'employe_id')::bigint as employe_id,
           coalesce((element->>'prime')::numeric, 0) as prime,
           coalesce((element->>'total_paye')::numeric, 0) as total_paye
    from jsonb_array_elements(p_remunerations) element
  loop
    insert into public.archives_rh (
      periode_id, employe_id, employe_nom, ca_ventes, prime, total_paye
    )
    select periode.id, employe.id, employe.nom_prenom,
      coalesce(sum(transaction.prix_total), 0), remuneration.prime, remuneration.total_paye
    from public.employes employe
    left join public.transactions transaction
      on transaction.vendeur_id = employe.id
      and transaction.periode_id = periode.id
      and transaction.type_transaction in ('Vente', 'Vente Employé')
    where employe.id = remuneration.employe_id
    group by employe.id, employe.nom_prenom;
    if not found then
      raise exception 'Employé % introuvable pour l''archive RH', remuneration.employe_id;
    end if;
  end loop;

  update public.employes set prime_actuelle = 0;
  -- Le registre des tickets constitue un historique permanent. Le quota est
  -- calculé par session de jeu et ne dépend pas des périodes comptables.
  insert into public.periodes_comptables (date_debut) values (p_date_fin + 1);
  return periode.id;
end;
$$;

create or replace function public.auditer_fabrication()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  perform public.ecrire_journal_action(
    new.employe_id, 'Fabrication confirmée', 'fabrication', new.id::text,
    new.produit_nom, null, to_jsonb(new),
    jsonb_build_object('quantite_produite', new.quantite_produite, 'nombre_crafts', new.nombre_crafts)
  );
  return new;
end;
$$;

create or replace function public.auditer_commande_journal()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  perform public.ecrire_journal_action(
    new.employe_id, new.action || ' de commande', 'commande', new.commande_reference::text,
    'Commande #' || new.commande_reference,
    case when new.statut_avant is null then null else jsonb_build_object('statut', new.statut_avant) end,
    case when new.statut_apres is null then null else jsonb_build_object('statut', new.statut_apres) end,
    jsonb_build_object('commande', new.commande_snapshot)
  );
  return new;
end;
$$;

create or replace function public.auditer_permis()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_employe_id bigint;
  v_action text;
begin
  if not old.document_sell and new.document_sell then
    v_employe_id := new.retire_par;
    v_action := 'Retrait de permis confirmé';
  elsif old.statut is distinct from new.statut then
    v_employe_id := new.valide_par;
    v_action := case new.statut when 'validé' then 'Validation de permis' when 'interdit' then 'Interdiction de permis' else 'Modification de permis' end;
  else
    return new;
  end if;
  if v_employe_id is not null then
    perform public.ecrire_journal_action(
      v_employe_id, v_action, 'permis', new.id::text,
      new.candidat || ' — ' || new.type_permis,
      jsonb_build_object('statut', old.statut, 'document_vendu', old.document_sell),
      jsonb_build_object('statut', new.statut, 'document_vendu', new.document_sell),
      jsonb_build_object('client_id', new.client_id)
    );
  end if;
  return new;
end;
$$;

create or replace function public.verifier_acces_direction(p_employe_id bigint, p_mot_de_passe text)
returns boolean
language sql
security definer
set search_path = public, extensions
stable
as $$
  select exists (
    select 1
    from public.employes e
    cross join public.mots_de_passe_direction m
    where e.id = p_employe_id
      and e.actif
      and e.grade in ('Patron', 'Co-Patron')
      and m.mot_de_passe_hash = extensions.crypt(p_mot_de_passe, m.mot_de_passe_hash)
  );
$$;

-- Triggers

create trigger set_updated_at
before update on public.employes
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.catalogue
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.clients
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.stocks
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.recettes_craft
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.commandes
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.lignes_commandes
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.inscriptions_permis
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.permis
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.mots_de_passe_direction
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.periodes_comptables
for each row execute function public.mettre_a_jour_updated_at();

create trigger set_updated_at
before update on public.client_permits
for each row execute function public.mettre_a_jour_updated_at();

create trigger preparer_transaction
before insert on public.transactions
for each row execute function public.preparer_transaction();

create trigger preparer_commande
before insert on public.commandes
for each row execute function public.preparer_commande();

create trigger preparer_ligne_commande
before insert on public.lignes_commandes
for each row execute function public.preparer_ligne_commande();

create trigger recalculer_total_commande
after insert or update or delete on public.lignes_commandes
for each row execute function public.recalculer_total_commande();

create trigger auditer_fabrication
after insert on public.fabrications
for each row execute function public.auditer_fabrication();

create trigger auditer_commande_journal
after insert on public.commandes_journal
for each row execute function public.auditer_commande_journal();

create trigger auditer_permis
after update on public.permis
for each row execute function public.auditer_permis();

-- Row-level security

alter table public.employes enable row level security;

alter table public.catalogue enable row level security;

alter table public.clients enable row level security;

alter table public.stocks enable row level security;

alter table public.recettes_craft enable row level security;

alter table public.transactions enable row level security;

alter table public.commandes enable row level security;

alter table public.lignes_commandes enable row level security;

alter table public.registre_tickets enable row level security;

alter table public.registre_tresorerie enable row level security;

alter table public.periodes_comptables enable row level security;

alter table public.archives_rh enable row level security;

alter table public.inscriptions_permis enable row level security;

alter table public.permis enable row level security;

alter table public.fabrications enable row level security;

alter table public.fabrications_ingredients enable row level security;

alter table public.commandes_journal enable row level security;

alter table public.client_permits enable row level security;

alter table public.journal_actions enable row level security;

alter table public.mots_de_passe_direction enable row level security;

create policy "Accès ERP local" on public.employes
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.catalogue
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.clients
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.stocks
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.recettes_craft
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.transactions
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.commandes
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.lignes_commandes
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.registre_tickets
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.registre_tresorerie
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.periodes_comptables
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.archives_rh
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.inscriptions_permis
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.permis
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.fabrications
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.fabrications_ingredients
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.commandes_journal
for all to anon, authenticated using (true) with check (true);

create policy "Accès ERP local" on public.client_permits
for all to anon, authenticated using (true) with check (true);

create policy "Lecture du journal ERP" on public.journal_actions
for select to anon, authenticated using (true);

-- Permissions

grant usage on schema public to anon, authenticated;

grant select, insert, update, delete on
  public.employes, public.catalogue, public.clients, public.stocks,
  public.recettes_craft, public.transactions, public.commandes,
  public.lignes_commandes, public.registre_tickets, public.registre_tresorerie,
  public.periodes_comptables, public.archives_rh, public.inscriptions_permis,
  public.permis, public.fabrications, public.fabrications_ingredients,
  public.client_permits
to anon, authenticated;
grant select, insert on public.commandes_journal to anon, authenticated;
grant select on public.journal_actions to anon, authenticated;
grant select on
  public.transactions_courantes, public.periode_comptable_courante,
  public.performances_employes, public.historique_comptable,
  public.employes_actifs, public.catalogue_actif, public.clients_actifs,
  public.commandes_en_cours, public.tresorerie_courante
to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

grant execute on function public.incrementer_stock(bigint, integer) to anon, authenticated;
grant execute on function public.decrementer_stock(bigint, integer) to anon, authenticated;
grant execute on function public.cout_revient_article(bigint, bigint[]) to anon, authenticated;
grant execute on function public.enregistrer_vente(bigint, jsonb, numeric, text) to anon, authenticated;
grant execute on function public.enregistrer_rachat(bigint, jsonb) to anon, authenticated;
grant execute on function public.enregistrer_frais(bigint, text, numeric) to anon, authenticated;
grant execute on function public.fabriquer_article(bigint, bigint, integer) to anon, authenticated;
grant execute on function public.creer_commande(bigint, bigint, date, jsonb, text) to anon, authenticated;
grant execute on function public.cloturer_periode(date, jsonb) to anon, authenticated;
grant execute on function public.session_jeu(timestamptz) to anon, authenticated;
grant execute on function public.enregistrer_panier(bigint, jsonb, bigint, jsonb) to anon, authenticated;
grant execute on function public.changer_statut_commande(bigint, text) to anon, authenticated;
grant execute on function public.valider_passage_permis(bigint, bigint, text) to anon, authenticated;
grant execute on function public.enregistrer_controle_tresorerie(bigint, numeric, text) to anon, authenticated;
grant execute on function public.enregistrer_achat_employe(bigint, jsonb) to anon, authenticated;
grant execute on function public.gerer_commande(bigint, bigint, text) to anon, authenticated;
grant execute on function public.enregistrer_client_permit(bigint, bigint, text, text, bigint) to anon, authenticated;
grant execute on function public.creer_client(text, text, bigint) to anon, authenticated;
grant execute on function public.modifier_client(bigint, text, text, bigint) to anon, authenticated;
grant execute on function public.archiver_client(bigint, text, bigint) to anon, authenticated;
grant execute on function public.enregistrer_panier_employe(bigint, jsonb, bigint) to anon, authenticated;
grant execute on function public.verifier_acces_direction(bigint, text) to anon, authenticated;

revoke all on table public.mots_de_passe_direction from anon, authenticated;
revoke all on function public.ecrire_journal_action(bigint, text, text, text, text, jsonb, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.journaliser_action_client(bigint, text, text, text, text, bigint, jsonb, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.verifier_acces_direction(bigint, text) from public;
grant execute on function public.verifier_acces_direction(bigint, text) to anon, authenticated;
comment on function public.verifier_acces_direction(bigint, text) is
  'Vérifie côté serveur le rôle actif et un mot de passe Direction haché.';

